
'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { createContext, useState } from 'react'
import Context from '@/interfaces/context'
import { Provider } from 'react-redux'
import { store } from '@/redux/store'
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css";
import ModalLogin from './(buyer)/login/ModalLogin.tsx'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const initialContext: Context = {
  productId: '',
  handleClickProduct: () => { },
  statusAddToCart: () => { },
  isAddToCart: false
}
export const Context = createContext<Context>(initialContext)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isAddToCart, setIsAddToCart] = useState(false)
  const [productId, setProductId] = useState<string>('');
  const handleClickProduct = (productId: string) => {
    setProductId(productId);
  };
  const statusAddToCart = () => {
    setIsAddToCart(!isAddToCart)
  }
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <Provider store={store}>

          <main>

            {children}
          <ModalLogin />
          </main>
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </Provider>
      </body>

    </html>
  );
}
