
'use client'
import Header from '@/components/Header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { createContext, useState } from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const ProductContext= createContext({})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const [productId, setProductId] = useState<Number>(0);

  const handleClickProduct = (productId: number) => {
    setProductId(productId);
  };
  return (
    <html lang="en">
      <head>
      <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
      </head>
      <body className={inter.className}>
        <ProductContext.Provider value={{productId,handleClickProduct}} >
          <main>
            
            {children}
          </main>
        </ProductContext.Provider>
      </body>

    </html>
  );
}
